sudo: true
dist: focal
language: python
python:
- '3.8'
branches:
 only:
   - master
env:
  matrix:
  - TOX_ENV=test
  - TOX_ENV=checkmigrations
  - TOX_ENV=behave
  - TOX_ENV=flake8
install:
- sudo apt-get update
- sudo apt-get install -y libsndfile1 sox normalize-audio
- pip install tox
- mkdir liokim
- cp tests/SuiSiannAdminApp/commands/Oct\ 13\,\ 2018\ _243.wav liokim
script:
- tox -e $TOX_ENV
