version: '3.5'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    networks:
      - default
      - nginx-bridge
    volumes:
      - "./wavs:/user/share/nginx/html/wavs:ro"
    environment:
       VIRTUAL_HOST: "suisiann-kautui.ithuan.tw"
       LETSENCRYPT_HOST: "suisiann-kautui.ithuan.tw"
       LETSENCRYPT_EMAIL: "ithuan@ithuan.tw"
    restart: always
  gunicorn:
    build: .
    volumes:
      - "./tsu-liāu:/djangoAdmin/tsu-liāu"
      - "./wavs:/djangoAdmin/wavs:ro"
    networks:
      default:
        aliases:
          - suisiann-kautui-autuan
    restart: always
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: ithuan
    volumes:
      - "postgres_database:/var/lib/postgresql/data"
    restart: always
  it:
    image: kaldi-tuitse_it
    expose:
      - 5000
    volumes:
      - './wavs/:/wav/:ro'
      - kaldis5:/kaldis5
    restart: always
  ji:
    image: kaldi-tuitse_ji_fst_decoding
    expose:
      - 5000
    volumes:
      - './wavs/:/wav/:ro'
      - kaldis5:/kaldis5
    restart: always
  sam:
    image: kaldi-tuitse_sam_sikan
    expose:
      - 5000
    volumes:
      - kaldis5:/kaldis5
    restart: always

volumes:
  kaldis5:
  postgres_database:

networks:
  nginx-bridge:
    external: true
