version: '3.5'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    networks:
      - default
      - nginx-bridge
    environment:
       VIRTUAL_HOST: "suisiann-kautui.ithuan.tw"
       LETSENCRYPT_HOST: "suisiann-kautui.ithuan.tw"
       LETSENCRYPT_EMAIL: "ithuan@ithuan.tw"
    restart: always
  gunicorn:
    build: .
    volumes:
      - "./wavs:/djangoAdmin/wavs:ro"
    networks:
      default:
        aliases:
          - suisiann-kautui-autuan
    restart: always
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: ithuan
    volumes:
      - "postgres_database:/var/lib/postgresql/data"
    restart: always

volumes:
  postgres_database:

networks:
  nginx-bridge:
    external: true
