version: '3.5'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    networks:
      - default
      - nginx-bridge
    volumes:
      - "staticfiles:/usr/share/nginx/html/static:ro"
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST:-suisiann-kautui.ithuan.tw}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST:-suisiann-kautui.ithuan.tw}
      - LETSENCRYPT_EMAIL=ithuan@ithuan.tw
    restart: always
  gunicorn:
    build: .
    volumes:
      - "staticfiles:/staticfiles:rw"
    networks:
      default:
        aliases:
          - suisiann-kautui-autuan
    restart: always
    environment:
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      DJANGO_SETTINGS_MODULE: SuiSiannAdmin.settings-tsiunnsuann
      HOKBU_DOMAIN_NAME: ${VIRTUAL_HOST:-suisiann-kautui.ithuan.tw}
      SECRET_KEY: ${SECRET_KEY}
      SENTRY_DSN: ${SENTRY_DSN}
  postgres:
    image: postgres:15
    labels:
      - backup.postgres=true
    environment:
      POSTGRES_PASSWORD: ithuan
    volumes:
      - "postgres_database:/var/lib/postgresql/data"
    restart: always

  # ling_kaldi_format:
  #   image: kaldi-liau_ling_kaldi_format
  #   volumes:
  #     - './liokim/:/wav/:ro'
  #     - kaldis5:/kaldis5
  #   restart: always
  # it_poolmj:
  #   image: kaldi-liau_it_poolmj
  #   volumes:
  #     - kaldis5:/kaldis5
  #   restart: always
  # ji_fst_decoding_koh_rescoring:
  #   image: kaldi-liau_ji_fst_decoding_koh_rescoring
  #   volumes:
  #     - './liokim/:/wav/:ro'
  #     - kaldis5:/kaldis5
  #   restart: always
  # sam_sikan:
  #   image: kaldi-liau_sam_sikan
  #   volumes:
  #     - kaldis5:/kaldis5
  #   restart: always

volumes:
  postgres_database:
  kaldis5:
  staticfiles:

networks:
  nginx-bridge:
    external: true
