version: '3.5'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    networks:
      - default
      - nginx-bridge
    volumes:
      - "./台灣媠聲:/usr/share/nginx/html/suisiann:ro"
      - "./media:/usr/share/nginx/html/media:ro"
      - "staticfiles:/usr/share/nginx/html/static:ro"
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST:-suisiann-kautui.ithuan.tw}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST:-suisiann-kautui.ithuan.tw}
      - LETSENCRYPT_EMAIL=ithuan@ithuan.tw
    restart: always
  gunicorn:
    build: .
    volumes:
      - "./台灣媠聲:/台灣媠聲:ro"
      - "./汐止媠聲:/djangoAdmin/汐止媠聲:ro"
      - "./media:/djangoAdmin/media"
      - "./hue:/djangoAdmin/hue"
      - "staticfiles:/staticfiles:rw"
    networks:
      default:
        aliases:
          - suisiann-kautui-autuan
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=SuiSiannAdmin.settings-tsiunnsuann
      - VIRTUAL_HOST=${VIRTUAL_HOST:-suisiann-kautui.ithuan.tw}
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: ithuan
    volumes:
      - "postgres_database:/var/lib/postgresql/data"
    restart: always

  # ling_kaldi_format:
  #   image: kaldi-liau_ling_kaldi_format
  #   volumes:
  #     - './liokim/:/wav/:ro'
  #     - kaldis5:/kaldis5
  #   restart: always
  # it_poolmj:
  #   image: kaldi-liau_it_poolmj
  #   volumes:
  #     - kaldis5:/kaldis5
  #   restart: always
  # ji_fst_decoding_koh_rescoring:
  #   image: kaldi-liau_ji_fst_decoding_koh_rescoring
  #   volumes:
  #     - './liokim/:/wav/:ro'
  #     - kaldis5:/kaldis5
  #   restart: always
  # sam_sikan:
  #   image: kaldi-liau_sam_sikan
  #   volumes:
  #     - kaldis5:/kaldis5
  #   restart: always

volumes:
  postgres_database:
  kaldis5:
  staticfiles:

networks:
  nginx-bridge:
    external: true
